server:
    port: 8080

spring:
    application:
       name: poki
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL94Dialect
    datasource:
        url: jdbc:postgresql://localhost/fortunesdb
        username: postgres
        driverClassName: org.postgresql.Driver
        data: classpath:/quotes.sql
        hikari:
            connection-timeout: 2000
            maximum-pool-size: 10

---

spring:
    profiles: dev
    jpa:
        show-sql: true
  